export const themeLight = {
  active: 'light',
  logo: '/logo/logo-light.svg',
  logoFooter: '/logo/logo-footer-light.svg',
  code: 'light',
  canvas: '#744164',
  intro: `👋 Hi, my name is`,
  icons: {
    github: '/icons/github-light.svg',
    twitter: '/icons/twitter-light.svg',
    linkedin: '/icons/linkedin-light.svg',
    spotify: '/icons/spotify-light.svg',
    nft: '/icons/nft-dark.svg',
    download: '/icons/download-light.svg',
    external: '/icons/external-link-light.svg',
    search: '/icons/search-dark.svg',
    email: '/icons/email-light.svg',
    clipboard: '/icons/clipboard-dark.svg',
    time: '/icons/time-light.svg',
    error: '/icons/error-dark.svg',
  },
}

export const themeDark = {
  active: 'dark',
  logo: '/logo/logo-dark.svg',
  logoFooter: '/logo/logo-footer-dark.svg',
  code: 'dark',
  canvas: '#3dffc5',
  intro: `✌️ Hi, my name is`,
  icons: {
    github: '/icons/github-dark.svg',
    twitter: '/icons/twitter-dark.svg',
    linkedin: '/icons/linkedin-dark.svg',
    spotify: '/icons/spotify-dark.svg',
    nft: '/icons/nft-light.svg',
    download: '/icons/download-dark.svg',
    external: '/icons/external-link-dark.svg',
    search: '/icons/search-light.svg',
    email: '/icons/email-dark.svg',
    clipboard: '/icons/clipboard-light.svg',
    time: '/icons/time-dark.svg',
    error: '/icons/error-light.svg',
  }
}